-- Purchase Order Entries
CREATE TABLE IF NOT EXISTS po_entries (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  customer_name VARCHAR(255) NULL,
  customer_address TEXT NULL,
  state VARCHAR(100) NULL,
  country VARCHAR(100) NULL,
  gst_no VARCHAR(50) NULL,
  business_type VARCHAR(100) NULL,
  segment VARCHAR(100) NULL,
  zone VARCHAR(100) NULL,
  contract_agreement_no VARCHAR(100) NULL,
  ca_date DATE NULL,
  po_no VARCHAR(100) NULL,
  po_date DATE NULL,
  letter_of_intent_no VARCHAR(100) NULL,
  tender_date DATE NULL,
  description TEXT NULL,
  payment_type VARCHAR(100) NULL,
  payment_terms TEXT NULL,
  insurance_types VARCHAR(255) NULL,
  advance_bank_guarantee_no VARCHAR(100) NULL,
  abg_date DATE NULL,
  performance_bank_guarantee_no VARCHAR(100) NULL,
  pbg_date DATE NULL,
  sales_manager VARCHAR(100) NULL,
  sales_head VARCHAR(100) NULL,
  agent_name VARCHAR(100) NULL,
  agent_commission VARCHAR(100) NULL,
  delivery_schedule TEXT NULL,
  liquidated_damages VARCHAR(255) NULL,
  po_signed_concern_name VARCHAR(255) NULL,
  boq_as_per_po TEXT NULL,
  total_ex_works DECIMAL(15,2) NULL,
  freight_amount DECIMAL(15,2) NULL,
  gst DECIMAL(15,2) NULL,
  total_po_value DECIMAL(15,2) NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_po_entries_customer (customer_name),
  INDEX idx_po_entries_po_no (po_no),
  INDEX idx_po_entries_created (created_at)
);

