-- Add tax deduction columns to payments table
ALTER TABLE payments ADD COLUMN IF NOT EXISTS progressive_delivery DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER amount;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS agt_commissioning DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER progressive_delivery;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS gst_tds DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER agt_commissioning;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS it_tds DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER gst_tds;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS it_tds_u194q DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER it_tds;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS labour_cess DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER it_tds_u194q;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS old_it_tds DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER labour_cess;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS other_recovery DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER old_it_tds;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS penalty DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER other_recovery;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS customer_name VARCHAR(191) AFTER customer_id;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS project_name VARCHAR(191) AFTER customer_name;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS package_name VARCHAR(191) AFTER project_name;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_type VARCHAR(50) AFTER method;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS bank_name VARCHAR(191) AFTER payment_type;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS bank_credit_date DATETIME AFTER bank_name;
